hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/ecommerce
hibernate.connection.username=root
hibernate.connection.password=Prudhvi@1975
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true